### PR TITLE
Cache dotty-bootstrapped artifacts in Docker image

### PR DESCRIPTION
**Pull request by allanrenucci**

### CODE REVIEW

**Comment by OlivierBlanvillain** [comment]
LGTM

**Comment by smarter** [comment]
Instead of compile you should be able to do update to just download the dependencies.

**Comment by allanrenucci** [comment]
Here is my experiment: the docker image generated with `sbt update` is slightly smaller. I suspect it does not download as much as the others. I will try to run the tests with it to see if `sbt` needs to download more.

| Tag        | command                                          |  Size  |
|------------|--------------------------------------------------|:------:|
| test       | update                                           |  937MB |
| 2017-09-08 | ";test:compile ;dotty-bootstrapped/test:compile" | 1.05GB |
| 2017-09-05 | ";compile ;test:compile"                         |  978MB |

**Comment by smarter** [comment]
Right, you probably need `;test:update;dotty-bootstrapped/test:update`

**Pull request merged**
